#!/bin/bash

pacotes=(
	"fish" "fisher"  "xclip"  "openssh" "xsel"	 		
	"bspwm" "sxhkd" "rofi" "polybar"
	"git" "github-cli" "go" "pass" 
	"micro" "alacritty"
	"ttf-jetbrains-mono" 	 
    "wmname" 	
	"xdotool"
)

sudo pacman -Sy


# Itera sobre o array e exibe todos os elementos
for pk in "${pacotes[@]}"
do
    sudo pacman -S -q --needed --noconfirm $pk
done

sudo chsh -s /bin/fish $USER

